# numpy 


#### import library

In [1]:
import numpy as np
import pandas as pd


#### List

In [2]:
a= np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


#### Matrix

In [3]:
b= np.array([[9.0,8.0,7.0],
             [6.0,5.0,4.0]], dtype='int32')
print(b)

[[9 8 7]
 [6 5 4]]


### get dimension to the data


In [4]:
a.ndim

1

In [5]:
b.ndim

2

### get shape to the data

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

### get type to the data

In [8]:
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('int32')

### get size to the data

In [10]:
a.itemsize

4

In [11]:
b.itemsize

4

### get total size to the data

In [12]:
print(a.size * a.itemsize)
#or
print(a.nbytes)

12
12


In [13]:
b.nbytes

24

## Accessing/Changing specific elements , rows ,columns , ect....

### get specific element [row , column]

In [14]:
x= np.array([[1,2,3,4,5,6,7],
             [8,9,10,11,12,13,14]])
print(x)

x[1,5]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


np.int64(13)

### get specific row

In [15]:
x[0, :]

array([1, 2, 3, 4, 5, 6, 7])

### get specific coloumn

In [16]:
x[: ,2]

array([ 3, 10])

### get a little more fancy [startindex:endindex:stepsize]

In [17]:
x[0, 1:-1:2]

array([2, 4, 6])

In [18]:
x[0,-2]=8
x

array([[ 1,  2,  3,  4,  5,  8,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
x[:,1]=5
x

array([[ 1,  5,  3,  4,  5,  8,  7],
       [ 8,  5, 10, 11, 12, 13, 14]])

In [20]:
x[:,3]=[100,101]
x

array([[  1,   5,   3, 100,   5,   8,   7],
       [  8,   5,  10, 101,  12,  13,  14]])

In [21]:
b= np.array([[[1,2],
              [3,4]],
              [[5,6],
              [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### get specific element (work outside in)

In [22]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

### replace

In [23]:
b[:,0,0] = [12,13]
print(b)
print('_or_')
#or
b[:,0,:] = [[14],[15]]
print(b)

[[[12  2]
  [ 3  4]]

 [[13  6]
  [ 7  8]]]
_or_
[[[14 14]
  [ 3  4]]

 [[15 15]
  [ 7  8]]]


### all 0s matrix

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [27]:
np.zeros((2,3,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [28]:
print('1st dimension : Block')
print('2nd dimension : sub-blocks')
print('3rd dimension : rows')
print('4th dimension : columns')

1st dimension : Block
2nd dimension : sub-blocks
3rd dimension : rows
4th dimension : columns


### all 1s matrix

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones((3,4,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

### any othe numbers matrix

In [31]:
ab= np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

In [32]:
np.full((2,2),21)

np.full((ab.shape),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

### any other number (full_like) matrix

In [33]:
print(ab)
print(ab.shape)

print(np.full_like(ab.shape,4))
print(np.full_like(ab,4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[4 4]
[[4 4 4 4 4]
 [4 4 4 4 4]]


### Random decimal numbers

In [34]:
np.random.rand(4,2)

array([[0.72256391, 0.64146798],
       [0.32455286, 0.23805974],
       [0.63461869, 0.13080485],
       [0.71497144, 0.5242343 ]])

In [35]:
np.random.rand(4,2,3)

array([[[0.95452832, 0.12007239, 0.35235548],
        [0.05060036, 0.98420793, 0.75816748]],

       [[0.17644487, 0.14822889, 0.31054513],
        [0.34592235, 0.93244441, 0.9684942 ]],

       [[0.25408551, 0.27481606, 0.34010911],
        [0.79545221, 0.68183416, 0.58432694]],

       [[0.41113746, 0.59803374, 0.33074131],
        [0.36035796, 0.43213646, 0.35473509]]])

In [36]:
np.random.random_sample(ab.shape)

array([[6.14409370e-01, 4.54125640e-01, 8.22255584e-01, 9.69378549e-01,
        3.41392565e-04],
       [7.33637960e-01, 7.38322603e-01, 3.12008401e-01, 2.29649392e-01,
        4.35074026e-01]])

### Random integer values

In [37]:
for i in range(1,6):
    print(np.random.randint(7))

5
3
3
0
4


In [38]:
np.random.randint(5,10,size=(3,4))

array([[8, 6, 5, 9],
       [6, 7, 5, 7],
       [6, 6, 9, 8]], dtype=int32)

### Identity matrix

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Repeat an array

In [40]:
arr = np.array([1,2,3])
r1=np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [41]:
arrr = np.array([[1,2,3]])
r2=np.repeat(arrr,3,axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [42]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### coping arrays 

In [43]:
a=np.array([1,2,3])
b = a
b[0]=100

print(b)
print(a)

[100   2   3]
[100   2   3]


In [44]:
a=np.array([1,2,3])
b = a.copy()
b[0]=100

print(b)
print(a)

[100   2   3]
[1 2 3]


## Mathematics

### Operation

In [45]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [46]:
a + 2

array([3, 4, 5, 6])

In [47]:
a - 2

array([-1,  0,  1,  2])

In [48]:
a * 2

array([2, 4, 6, 8])

In [49]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [50]:
b = a.copy()
b

array([1, 2, 3, 4])

In [51]:
b + a

array([2, 4, 6, 8])

### take the sin , cos 

In [52]:
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


### Linear Algebra

In [53]:
a =np.ones((2,3))
print(a)

b=np.full((3,2) ,2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

### Find the determinant

In [54]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

### Statistics

In [55]:
stats=np.array([[1,2,3],
                [4,5,6]])
print(stats)
print(stats.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [56]:
print(np.min(stats,axis=1))

print('No Axis : search in all list')
print('Axis = 0 : search in Rows')
print('Axis = 1 : search in Columns')

[1 4]
No Axis : search in all list
Axis = 0 : search in Rows
Axis = 1 : search in Columns


In [57]:
np.max(stats)

np.int64(6)

In [58]:
print(np.sum(stats))
print(np.sum(stats[0]))
print(np.sum(stats[1]))
print(np.sum(stats,axis=0))
print(np.sum(stats,axis=1))

21
6
15
[5 7 9]
[ 6 15]


### Reorganizing Arrays

In [59]:
before = np.array([[1,2,3,4],
                [5,6,7,8]])
print(before)

after= before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### Vertically stacking vectors

In [60]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v1,v2]))


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


### Horizontal stacking vactors

#### for matrix and vector

In [61]:
h1=np.ones((2,4))
h2=np.zeros((2,2))

print(np.hstack((h1,h2)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


#### for vector

In [62]:
c1=np.array([1,2,3,4])
c2=np.array([5,6,7])

print(np.concatenate((c1,c2)))

[1 2 3 4 5 6 7]


### Miscellaneous
###### Load Data from File

In [63]:
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
# astype : show datas by types
filedata


array([[10, 85, 14, 16, 16, 84, 66, 35, 26, 65, 50, 58, 39, 29, 98, 14,
        21, 74],
       [48, 92, 52, 44, 42, 37, 68, 62, 50, 42, 26, 37, 47, 50, 13, 48,
        19, 31],
       [84, 10, 79, 50, 54, 86, 65, 82, 51, 59, 46, 42, 49,  2, 23, 18,
        51, 67]], dtype=int32)

#### Boolean Masking and Advanced Indexing

In [64]:
filedata > 50

array([[False,  True, False, False, False,  True,  True, False, False,
         True, False,  True, False, False,  True, False, False,  True],
       [False,  True,  True, False, False, False,  True,  True, False,
        False, False, False, False, False, False, False, False, False],
       [ True, False,  True, False,  True,  True,  True,  True,  True,
         True, False, False, False, False, False, False,  True,  True]])

In [65]:
filedata[filedata > 50]

array([85, 84, 66, 65, 58, 98, 74, 92, 52, 68, 62, 84, 79, 54, 86, 65, 82,
       51, 59, 51, 67], dtype=int32)

In [66]:
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [67]:
np.any(filedata > 50 , axis=0)

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True, False,  True,  True])

In [68]:
np.any(filedata > 50 , axis=1)

array([ True,  True,  True])

In [69]:
print(((filedata > 50) & (filedata < 100)))

print('_____reverse_____')

print((~((filedata > 50) & (filedata < 100))))

[[False  True False False False  True  True False False  True False  True
  False False  True False False  True]
 [False  True  True False False False  True  True False False False False
  False False False False False False]
 [ True False  True False  True  True  True  True  True  True False False
  False False False False  True  True]]
_____reverse_____
[[ True False  True  True  True False False  True  True False  True False
   True  True False  True  True False]
 [ True False False  True  True  True False False  True  True  True  True
   True  True  True  True  True  True]
 [False  True False  True False False False False False False  True  True
   True  True  True  True False False]]


In [72]:
np.__version__


'2.2.5'